{{- if ne .Values.sandboxId "default" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "datadog-agent-{{ Values.namespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datadog-agent
subjects:
  - kind: ServiceAccount
    name: deployment-runner
    namespace: "{{.Release.Namespace}}"
{{- end }}
